### ISSUE TITLE
pyenv issue

### ISSUE THREAD

**Issue by troublestarter** [MailCleaner/MailCleaner#363]
Hi,

- When firewall is launched :
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
/usr/mailcleaner/etc/init.d/firewall: 37: /usr/mailcleaner/etc/init.d/firewall: fail2ban.py: not found

- Tried this : https://github.com/pyenv/pyenv/issues/1906
=> the replacement correct the problem for pyenv warning

Have a look here :
https://forum.mailcleaner.org/viewtopic.php?f=12&p=13305&t=3237&sid=84376b889b64c5014f0b7f006705c5b0

**Comment by JohnMertz** [comment]
Hello,

#364 and a matching PR for Updater4MC were just merged which will remove the definition of the pyenv path from the root user's bash configurations and instead source them from a .bashrc file inside this repo. This will allow us to keep the configuration updated within the Git tree rather than blindly writing to a file outside the tree. Other necessary files are also updated. The Updater4MC script will reinstall fail2ban and it's dependencies if necessary during the next nightly update.

**Comment by troublestarter** [comment]
The update a fix a lot things.

But i can't enable the jails

root@mail-protection.my-cosi.info:~$ /var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py general enable
ERROR  Could not find server
Traceback (most recent call last):
  File "/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py", line 445, in <module>
    cli()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py", line 224, in gen_enable
    ret = f2b.enable_all_jail()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/fail2ban/fail2ban_service.py", line 324, in enable_all_jail
    ret[jail[0]] = self.enable_jail(jail[0])
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/fail2ban/fail2ban_service.py", line 317, in enable_jail
    jail_name))
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/fail2ban/fail2ban_service.py", line 511, in __safe_run
    command.stdout))
mailcleaner.fail2ban.fail2ban_service.Fail2banException: An error occured during the run of the command fail2ban-client -c /usr/mailcleaner/etc/fail2ban/ reload mc-exim with the following exit_code: 255
 Stderr: ERROR  Could not find server

 Stdout:

**Comment by d-jorg** [comment]
Hello,

it seems that fail2ban isn't started at all. 
Run the following command and you should be able to set the jails afterwards 
`/usr/mailcleaner/etc/init.d/fail2ban restart`

**Comment by troublestarter** [comment]
I can confirm all is OK now.
The service is enbale at boot time ?

**Comment by JohnMertz** [comment]
Will be started with Firewall in #450
