### ISSUE TITLE
Major problems with pyenv / fail2ban

### ISSUE THREAD

**Issue by David-in-NZ** [MailCleaner/MailCleaner#397]
Hi All
I am having real problems and am totally stumped - I'm new to much of this so please be gentle with me!

I have a new installation of Mailcleaner which is working well, apart from the fact that it is getting 10's of 1000's of smtp brute force hits every day.  To address this I went to enable fail2ban as per https://support.mailcleaner.net/boards/3/topics/80-fail2ban

However when I run `/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py` I get a file not found error and sure enough I do not have a .pyenv directory in /var/mailcleaner. I tried to do a search for fail2ban.py but it was not found anywhere on my system.

In attempting to address this I discovered that the updates were failing - also because of the missing .pyenv directory.

I was able to manually install pyenv with `git clone https://github.com/pyenv/pyenv.git /var/mailcleaner/.pyenv` and then I  removed the files in /var/mailcleaner/spool/updater and then re-ran the updater4mc.sh script but by the time it finished the .pyenv directory had been removed and I was back where I started.

I'd really appreciate some help with this as I've been banging my head against it for hours.  I've posted all this on the mailcleaner support forum but have not had any reply.

update log it attached - all done logged in as root.

Thanks in advance!
[updater4mc.log](https://github.com/MailCleaner/MailCleaner/files/7210213/updater4mc.log)

**Comment by aqumo** [comment]
Hi All,
after running the daily update (cron script) on September 22, fail2ban no longer works.
Log in "/var/log/fail2ban.log" stopped on the evening of September 22nd.
If I try to run the "fail2ban.py general enable" command I get the following errors:

/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py general enable
ERROR Could not find server
Traceback (most recent call last):
File "/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py", line 445, in <module>
cli ()
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main (* args, ** kwargs)
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke (ctx)
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result (sub_ctx.command.invoke (sub_ctx))
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result (sub_ctx.command.invoke (sub_ctx))
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke (self.callback, ** ctx.params)
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
return callback (* args, ** kwargs)
File "/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py", line 224, in gen_enable
ret = f2b.enable_all_jail ()
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/fail2ban/fail2ban_service.py", line 324, in enable_all_jail
ret [jail [0]] = self.enable_jail (jail [0])
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/fail2ban/fail2ban_service.py", line 317, in enable_jail
jail_name))
File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/fail2ban/fail2ban_service.py", line 511, in __safe_run
command.stdout))
mailcleaner.fail2ban.fail2ban_service.Fail2banException: An error occured during the run of the command fail2ban-client -c / usr / mailcleaner / etc / fail2ban / reload mc-exim with the following exit_code: 255
Stderr: ERROR Could not find server

Stdout:

I believe that some changes in the update caused the fail2ban to be aborted.
Is any resolution underway?
Thanks in advanced

**Comment by p-rolle** [comment]
Hello,
can you please report it to https://forum.mailcleaner.org/ ans have a direct contact with me "Pascal" ?
Did you make sure fail2ban-server is running :
ps fauxw |grep -i fail2ban-server
if not does "fail2ban-server start" or "/usr/mailcleaner/etc/init.d/fail2ban restart" solve the issue ?
Best regards,

**Comment by aqumo** [comment]
Hello,
thanks for answer, i did.
My nick is "aqumo", i put same message
Regards
Dario

**Comment by p-rolle** [comment]
Hello,

thanks to your report, we could find the issue, we will provide a fix ASAP.

Best regards,

**Comment by aqumo** [comment]
You're welcome
Best regards,

**Comment by p-rolle** [comment]
To solve the issue right away, please run

/root/Updater4MC/updater4mc.sh
/usr/mailcleaner/etc/init.d/fail2ban restart
