### ISSUE TITLE
Fail2ban doesn't work with newest MarkupSafe 2.1.1

### ISSUE THREAD

**Issue by bogdankruszewski** [MailCleaner/MailCleaner#439]
When you try to install a new instance of MailCleaner today and execute Updater4mc, it will install Fail2ban with the newest Python MarkupSafe 2.1.1 dependency.

It will end in the following error, if you try to start the service or execute fail2ban.py:
`root@mailcleaner:/var/mailcleaner/.pyenv/versions/3.7.7/bin$ fail2ban.py
Traceback (most recent call last):
  File "/var/mailcleaner/.pyenv/versions/3.7.7/bin/fail2ban.py", line 6, in <module>
    from mailcleaner.fail2ban.fail2ban_service import Fail2banService
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/__init__.py", line 16, in <module>
    from .dumper import *
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/dumper/__init__.py", line 3, in <module>
    from .DumpMySQLConfig import DumpMySQLConfig
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/dumper/DumpMySQLConfig.py", line 4, in <module>
    from mailcleaner.dumper.MailCleanerBaseDump import MailCleanerBaseDump
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/mailcleaner/dumper/MailCleanerBaseDump.py", line 4, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markupsafe/__init__.py)
`

It looks like "soft_unicode" was removed from MarkupSafe in Version 2.1 and newer.
To resolve the issue as a workaround, you need to downgrade MarkupSafe to 2.0.1 with the following command:
`pip install markupsafe==2.0.1`

After this command Fail2ban service will start correctly and you can also use the fail2ban.py.

**Comment by reivilob** [comment]
Hi Bogdan could you contact me by email bourgeois@mailcleaner.net ?
regards
Olivier Bourgeois

**Comment by bogdankruszewski** [comment]
@reivilob , done.

Best regards

Bogdan

**Comment by bogdankruszewski** [comment]
@JohnMertz linking your #442 PR here. As far as I can see the PR is only installing the correct version on a new installation of the Python Mailcleaner libraries. "Old" installations, which already have MarkupSafe > 2.0.1 won't be downgraded. My PR https://github.com/MailCleaner/Updater4MC/pull/55 will downgrade it, if necessary, If not, MarkupSafe will remain untouched.
