### ISSUE TITLE
Mailcleaner fail2ban config results in error

### ISSUE THREAD

**Issue by hoppa123** [MailCleaner/MailCleaner#502]
since the latest update  my fail2ban isnt working anymore. it results in an access denied at the mysql server.. What am i doing wrong or what has gone wrong ? I even get the same error when i want to restart the daemon.

 

$ fail2ban.py general enable

Traceback (most recent call last):
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/mailcleaner/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'mailcleaner'@'localhost' (using password: YES)")

**Comment by JohnMertz** [comment]
There have been a large number of changes to fail2ban since this issue was created. If you are still having problems, please try re-installing with:

/usr/mailcleaner/install/install_pyenv_3-7-7.sh

then make sure that you are fully up-to-date with:

/root/Updater4MC/updater4mc.sh

If you continue having problems after that, please open a new issue.
